### ISSUE TITLE
httputil.get_gontent('http://91porn.com/index.php')出现错误

### ISSUE THREAD

**Issue by qishiJade** [lyrl/91porn#1]
>>> httputil.get_content('http://91porn.com/index.php')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "httputil.py", line 31, in get_content
    return urllib2.urlopen(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer

**Comment by 7475724** [comment]
File "C:\Users\zd729\Desktop\91porn-master\main.py", line 23, in <module>
    porn.download(link)
  File "C:\Users\zd729\Desktop\91porn-master\components\porn91.py", line 45, in download
    httputil.download_file('%s.mp4' % title, url)
  File "C:\Users\zd729\Desktop\91porn-master\components\httputil.py", line 35, in download_file
    urllib.urlretrieve(url, file_name, show_progress)
  File "C:\Python27\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Python27\lib\urllib.py", line 289, in retrieve
    "of %i bytes" % (read, size), result)
urllib.ContentTooShortError: retrieval incomplete: got only 60220540 out of 162757450 bytes

**Comment by lyrl** [comment]
墙内是没法访问的，需要对Python进行代理，或者在境外服务器执行

**Comment by huangyn-pku** [comment]
懂了，谢谢，我加上代理之后可以用了
